version: '3.8'

services:
  getcid_backend:
    build: .
    container_name: getcid_backend
    restart: always
    volumes:
      # Mapeamos el archivo de sesión para que el demonio lo lea y lo modifique
      - ./session_master.json:/app/session_master.json
      # Mapeamos la carpeta de logs para persistencia
      - ./logs:/app/logs
    environment:
      - TZ=America/Lima # Configurar tu zona horaria local

  getcid_frontend:
    build: ./frontend
    container_name: getcid_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/data:/app/data
      - ./frontend/uploads:/app/uploads
      # Mapeamos la carpeta de logs compartida
      - ./logs:/app/logs
    command: sh -c "mkdir -p /app/logs && node index.js >> /app/logs/frontend.log 2>&1"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - WC_URL=${WC_URL}
      - WC_CONSUMER_KEY=${WC_CONSUMER_KEY}
      - WC_CONSUMER_SECRET=${WC_CONSUMER_SECRET}
      - GETCID_SERVICE_URL=http://getcid_backend:8000
    depends_on:
      - getcid_backend

  getcid_auto_extractor:
    build: ./extractor_service
    container_name: getcid_auto_extractor
    restart: always
    ports:
      - "6080:6080"
    environment:
      - MS_EMAIL=${MS_EMAIL}
      - MS_PASSWORD=${MS_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${BOT_TOKEN}
      - TELEGRAM_ADMIN_ID=${ADMIN_IDS}
    shm_size: '2gb'
